#!/bin/sh
### BEGIN INIT INFO
# Provides:          fanRADIO
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       fanRADIO
### END INIT INFO

start() {
  if [ ! -d "/emRadio/" ]; then # init dir if not done yet
	mkdir /emRadio/
	cd /emRadio/
	git init
	git remote add -t main-v1 -f main-v1 https://github.com/SV98Fanradio/embedded-fanradio.git
	git checkout main-v1
	git pull
	chmod u+x /emRadio/src/*.sh
  else # update from branch
	cd /emRadio/
	git pull
  fi
  cd /emRadio/src/
  sudo -u pi /emRadio/src/radio_init.sh &
}

stop() {
  pkill radio_init.sh
  pkill vlc
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
