#!/bin/bash
### BEGIN INIT INFO
# Provides:          fanRADIO
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       fanRADIO
### END INIT INFO

start() {

  if [ ! -f /etc/emradio.conf]; then
	touch /etc/emradio.conf
	echo 'BRANCH="main-v1"' >> /etc/emradio.conf
  fi
  source /etc/emradio.conf

  if [ ! -d "/emRadio/" ]; then # init dir if not done yet
	mkdir /emRadio/
	cd /emRadio/
	git init
	git remote add -t $BRANCH -f $BRANCH https://github.com/SV98Fanradio/embedded-fanradio.git
	git checkout $BRANCH
	git pull
	chmod ugo+x /emRadio/src/*.sh
else # update from branch
	cd /emRadio/
	git pull
fi
# run and update init scripts
cd /emRadio/src/
sudo -u pi /emRadio/src/radio_init.sh &
cp /emRadio/src/radiocontroller /etc/init.d/
}

stop() {
  pkill radio_init.sh
  pkill vlc
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
